name: Cypress Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Cypress
        run: npm install cypress --save-dev
      - name: Run Cypress test
        run: npx cypress run --env allure=true,allureReuseAfterSpec=true
      - name: Reports Generate
        if: ${{ failure() || success() }}
        run: npx allure generate allure-results --clean -o allure-report
      - name: Deploy Report
        uses: JamesIves/github-pages-deploy-action@v4.4.0 # GH Action
        if: ${{ failure() || success() }}
        with:
          branch: main
          folder: ./allure-report
          target-folder: ./docs
